### ISSUE TITLE
`QtEventReactor.timeout()`: `unorderable types: float() < NoneType()`

### ISSUE THREAD

**Issue by altendky** [sunu/qt5reactor#10]
I sometimes get:

```
<class 'TypeError'>: 
unorderable types: float() < NoneType()
----------------------------------------------------------------------
  File "c:\users\ieuser\desktop\src\st\venv\src\qt5reactor\qt5reactor.py", line 411, in iterate
    self.doIteration(delay, fromqt=True)
  File "c:\users\ieuser\desktop\src\st\venv\src\qt5reactor\qt5reactor.py", line 308, in doIteration
    if self.timeout() is None:
  File "c:\users\ieuser\desktop\src\st\venv\src\qt5reactor\qt5reactor.py", line 402, in timeout
    return min(t, 0.01)
```

See my (to be linked) commit that alleviates this.

Of course, if you think something else is wrong and another solution should be found I'll work on that.  I'll share an exact commit from https://github.com/altendky/st once I have it pushed.

**Comment by altendky** [comment]
main: https://github.com/altendky/st/tree/2b42d6577de5511ad091ecf7d2830135a1126e56
lib submodule: https://github.com/altendky/st/tree/35c327c8abc7f098fecfeabed8614668517048fb

**Comment by crwood** [comment]
Now that @bakbuk's [PR](https://github.com/sunu/qt5reactor/pull/8) has been merged, this should be fixed in master. Please let me know if you are still experiencing the same issue as I intend on cutting a new release soon (as @sunu has graciously given me maintainership of the package on PyPI -- thanks @sunu!).

**Comment by altendky** [comment]
Nice to see someone else that's interested in this lib.  The removal of the timeout() method seems a bit odd to me but I really don't know my way around twisted very well so...  The new code won't take the minimum of None though so this shouldn't be an issue anymore.

**Comment by bakbuk** [comment]
When I encountered this problem I went to #twisted on freenode and some very friendly guys over there helped me patch it. One of the things that came up (unrelated to the original issue, I believe) was indeed the removal of this method. It was long ago so I can't recall why this was suggested (to be honest, I'm not sure I understood back then either).

Thanks @crwood and @sunu for getting things moving!

**Comment by crwood** [comment]
As far as I can tell -- and I'm no Twisted expert either -- there was never really any need to override the `timeout()` method inside of `QtEventReactor` in the first place, since `QtEventReactor` inherits and calls `QtReactor`'s  `doIteration()` method (wherein the enforcement of a minimum value from `PosixReactorBase.timeout()` was already happening). In fact, the presence of the needless `timeout()` override (or, more precisely, the unchecked `min()` call _within_ that override that raised the exception) was, in this case, actually _preventing_ the original minimum-check from occurring on Windows (such that simply removing or commenting it out is sufficient to fix this issue).

Thanks again @bakbuk (and the good folks in #twisted) for the original patch -- and @altendky for the confirmation and alternative fix!
