### ISSUE TITLE
Do we really support py2?

### ISSUE THREAD

**Issue by altendky** [sunu/qt5reactor#29]
Do we really support py2 as described by `setup.py`?

https://github.com/sunu/qt5reactor/blob/0b1cb55e435df2a838d6b5a604a11671fe80a860/setup.py#L17-L19

I know that PyQt5 does, I don't know about PySide2, and since we don't have tests showing it I don't know if we really support it.

**Comment by crwood** [comment]
I believe that qt5reactor was originally forked/written for [a python2 project](https://github.com/nehbit/aether/tree/master/Aether%201) by @nehbit and, judging by the code changes made since then, the code hasn't changed in any way that would render it incompatible with python2. Anecdotally, I've used python2 with PyQt5/qt5reactor in the past and can confirm that it at least "worked" for my purposes then (though, as you correctly point out, the lack of proper tests makes it difficult to determine whether and to what extent it should be considered properly supported).

That being said, my inclination would be to keep python2 support in for the time being since at least works as it does previously (which, again, isn't saying very much) and doing so doesn't really require any extra work. It may, however, be a good idea to remove the 2.6 classifier since, if I recall correctly, Twisted no longer supports 2.6...

Thoughts?

**Comment by altendky** [comment]
Oh what fun it is not having wheels for a Python version that PyQt5 supports...  otherwise I'd just add the tests.  Anyways, I don't have a particular issue leaving 2.7 since you have some expectation it works.  It appears Twisted dropped 2.6 in 16.0

https://github.com/twisted/twisted/blob/c1610bab03cdaf36d2d64c67a6674de8d56479c0/NEWS#L4-L8
```
Twisted Core 15.5.0 (2015-11-28)
================================

This is the last Twisted release where Python 2.6 is supported, on any
platform. Python 3.5 (on POSIX) support has been added.
```

I'll go make a quick 2.6-dropping PR.
